multiversx/mx-sdk-dapp

src/apiCalls/configuration/getServerConfigurationForEnvironment.ts, src/apiCalls/configuration/index.ts, src/apiCalls/index.ts, src/apiCalls/transactions/getTransactionsByHashes.ts, src/apiCalls/transactions/index.ts, src/apiCalls/transactions/sendSignedTransactions.ts, src/constants/network.ts, src/contexts/OverrideDefaultBehaviourContext.tsx, src/contexts/types.ts, src/index.tsx, src/redux/DappProvider.tsx, src/redux/reducers.ts, src/redux/selectors/transactionsSelectors.ts, src/redux/store.ts, src/utils/account/getAccountShard.tsx, src/utils/smartContracts.ts, src/wrappers/AppInitializer.tsx
this PR:
- fixes error on RN because of redux-persist. Now the persist is conditioned by presence of localStorage and sessionStorage on the window object;
- exposes apiCalls for reuse across apps and the fallback configs;
- allows passing in EnvironmentEnum directly;
=> add support for React Native usage (except for persistence)

src/services/login/useWalletConnectLogin.ts, src/services/login/useWebWalletLogin.ts
Currently, we are still in error because we initialize `error` with an empty string, and `'' !== null`
I saw there was the same fix on `useExtensionLogin` not long ago.
=> Fix useWalletConnectLogin and useWebWalletLogin error flag

src/hooks/transactions/useParseSignedTransactions.tsx, src/hooks/transactions/useSignTransactions.tsx, src/services/transactions/hooks/useTrackTransactionStatus.ts
When user goes to web wallet and Cancels transactions, upon return, callbacks are no longer registered because user left the page. This PR re-enables the callbacks by restoring the previous session
=> [*] Web wallet triggering of onCancel and onFailed transactions

README.md
Readme has a typo, leading to confusion when using 2.0 (and the migration from 1.X)
=> Fix `accounts` import to `account` in the readme

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithWalletConnectModal/index.tsx, src/hooks/transactions/helpers/getShouldMoveTransactionsToSignedState.ts, src/hooks/transactions/helpers/index.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
If a  user cancels the sign flow from modal Cancel button, and signs the transactions afterwards from Ledger or Maiar App, the new signed transactions will be invalidated
=> Invalidate signed transactions after sign flow was canceled

CHANGELOG.md, package.json, src/wrappers/AuthenticatedRoutesWrapper/helpers/index.tsx, src/wrappers/AuthenticatedRoutesWrapper/helpers/matchPath.tsx, src/wrappers/AuthenticatedRoutesWrapper/helpers/matchRoute.ts, src/wrappers/AuthenticatedRoutesWrapper/helpers/tests/matchRoute.test.ts, src/wrappers/AuthenticatedRoutesWrapper/index.tsx
- add locally `matchPath` helper from react-router-dom
- create `matchRoute` helper used in `AuthenticatedRoutesWrapper`
- add tests
=> [+] AuthenticatedRoutesWrapper uses matchPath from react-router-dom to detect pattern routes

CHANGELOG.md, src/UI/Trim/trim.styles.scss
[*] Trim component on Safari:
- updated Safari support since iOS 16 now supports min-resolution
- reduced unused whitespace from text-overflow with letter-spacing
=> Fix trim component ios

CHANGELOG.md, src/UI/LoginButton/LoginButton.tsx, src/UI/extension/ExtensionLoginButton/index.tsx, src/UI/ledger/LedgerLoginButton/index.tsx, src/UI/walletConnect/WalletConnectLoginButton/index.tsx, src/UI/webWallet/WebWalletLoginButton/index.tsx, src/hooks/login/useExtensionLogin.ts, src/hooks/login/useLedgerLogin.ts, src/hooks/login/useWalletConnectLogin.ts, src/hooks/login/useWalletConnectV2Login.ts, src/hooks/login/useWebWalletLogin.ts, src/types/login.types.ts, src/utils/internal/optionalRedirect.ts
- allow consumer app to get access to signature directly from login hook
=> Extend onLoginRedirect with address and signature props

package.json, yarn.lock
This fixes CVE-2022-24999.
ref: https://github.com/n8tz/CVE-2022-24999
=> Bump @elrondnetwork/erdjs-web-wallet-provider to latest

src/services/transactions/signTransactions.ts
This PR allows dapp-core to be used in nextJS, except for UI components.
It's the usage of SCSS imports in TS/JS file that generates many document.createStyle in the build files which is not compatible in ssr.
So, if it's okay for you, we should avoid using SCSS import outside of UI components to allow NextJs users to use dapp-core, at least for hooks and services.
This is a quick fix to show the problem, but there is surely an abstraction issue, a service should not be aware of the display and therefore not return ui classes.
There may also be something to do at build time to make this system SSR compatible...but I don't know much about that.
=> :bug: nextjs support

CHANGELOG.md, src/components/ProviderInitializer.tsx
- stop leaving app in an intermediary state if address is not found from wallet login
=> Fix wallet cancelled login

README.md
Still shows version pre-rebranding
Before:
After:
=> Fix npm version displayed in readme

CHANGELOG.md, src/UI/ScamPhishingAlert/ScamPhishingAlert.tsx, src/services/nativeAuth/helpers/decodeNativeAuthToken.tsx, src/services/nativeAuth/helpers/tests/decodeNativeAuthToken.test.ts, src/services/nativeAuth/methods/getNativeAuthConfig.ts, src/services/nativeAuth/nativeAuth.ts, src/services/nativeAuth/tests/nativeAuth.test.ts, src/types/login.types.ts
Changed `host` and `hostname` to `origin` in `decodeNativeAuthToken` and `getNativeAuthConfig` return types. Added `authorizationInfo` prop in `ScamPhishinAlert` component
=> [+] NativeAuth origin and ScamPhishing auth message

CHANGELOG.md, src/services/nativeAuth/helpers/decodeLoginToken.ts
There is a confusion of when `decodeLoginToken` and `decodeNativeAuthToken` should be called and some users may accidentally call the wrong function
Call `decodeLoginToken` with a nativeAuthToken and an error will be thrown
Within the `decodeLoginToken` there is no check if the token is a login or nativeAuth one. There is such check in `decodeNativeAuthToken` function however.
Call `decodeNativeAuthToken` within `decodeLoginToken` if the token has 3 parts
```
if (parts.length === 3) {
return decodeNativeAuthToken(loginToken);
}
```
and call `decodeLoginToken` within `decodeNativeAuthToken` if the token has 4 parts
```
if (parts.length === 4) {
const parsedInitToken = decodeLoginToken(accessToken);
if (!parsedInitToken) {
return null;
}
const { ttl, extraInfo, origin, blockHash } = …
```
=> [+] Updated `decodeLoginToken` to call `decodeNativeAuthToken` when necessary

CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts, src/hooks/signMessage/verifyMessage.ts, src/utils/index.ts, src/utils/removeSearchParamsFromUrl.ts, src/utils/tests/removeSearchParamsFromUrl.test.ts, src/utils/transactions/removeTransactionParamsFromUrl.ts, yarn.lock
There was an error thrown in a dapp that was signing a message with `signMessageWithWallet`. The dapp was hanging and not redirecting to the wallet.
Also, in the web wallet, the `verifyMessage` did nothing.
Try to sign any message with the dapp-template using web wallet.
The `signMessage` and `verifyMessage` require a new `SignableMessage` encodings. Also, the `onAbort` method of `useSignMessage` hook did not clear the url params of the sign message context, causing the state to not be cleared.
- add to the `signMessage` method a `SignableMessage` with address and message correctly encoded.
- encode the signature correctly before passing it to `verifyMessage`
- clear the URL search params of the sign message context from `SignedMessageQueryParamsEnum`: `sessionId`, `signature`, `address`, …
=> [FIX] Fixed `signMessage` and `verifyMessage` did not receive correct params and did not clear state `onAbort`

CHANGELOG.md, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, src/hooks/transactions/helpers/index.ts, src/hooks/transactions/useSignMultipleTransactions.tsx, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
- transaction data for ledger was not set correctly when signing with guardian
Issue exists on version `2.12.2` of sdk-dapp.
- `hashSign` option was not being added to transactions
- add `hashSign` to `useSignMultipleTransactions`
- create `checkNeedsGuardianSigning` helper
[x] No
[] Yes
[x] Yes
[] Unit tests
=> 2fa hook ledger hashSign

CHANGELOG.md, src/types/tokens.types.ts
`ledgerSignature` is missing in `assets` field of `TokenType`
Issue exists on version `2.12.4` of sdk-dapp.
`ledgerSignature` is missing in `assets` field of `TokenType`
Add `ledgerSignature` in `assets` field of `TokenType`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] Added `ledgerSignature` to assets in `TokenType`

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/types/transactions.types.ts
- cannot perform change guardian address without access to guardian app
Issue exists on version `2.12.6` of sdk-dapp.
- allow setting customTransactionInformation skipGuardian
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Skip guardian

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/services/transactions/sendTransactions.ts, src/types/transactions.types.ts
- skipGuardian flag was not being passed from sendTransactions
Issue exists on version `2.12.7` of sdk-dapp.
- added skipGuardian flag to sendTransactions
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix skip guardian

.github/pull_request_template.md, CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts, yarn.lock
`signMessage` has 3 return types and does not return the signedMessage object (`SignableMessage`), only when calling `signMessageWithWallet`.
Issue exists on version `2.12.8` of sdk-dapp.
`signMessage` returns at `onCancel` and at store `dispatch` and does not return the signed message when we don't use `signMessageWithWallet`. These causes to have three return types: `Promise<void | SignableMessage | payload<{}>>`.
Return the signableMessage when possible and return null otherwise.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [FIX] Fixed incorrect returns of `signMessage`

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
- when skipGuardian was set, user was still being redirected to 2FA hook in wallet
Issue exists on version `2.12.8` of sdk-dapp.
- add condition for skipGuardian when checking if needs2FaSigning
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix guardian redirect

src/components/BatchTransactionsSender/BatchTransactionsSender.ts, src/hooks/transactions/batch/tracker/useUpdateBatch.ts, src/services/transactions/getTransactionsDetails.ts
Some batches are not processed by the service and have missing transaction hashes
Duplicate batch transactions send
Issue exists on version `2.13` of sdk-dapp.
Batch transactions service
Error in the batch transactions send flow (duplicate send)
Handle this case in order to resolve the toast with the correct status (notExecuted)
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix handle unsent batch transactions

CHANGELOG.md, src/reduxStore/selectors/index.ts, src/reduxStore/slices/dappConfigSlice.ts
`shouldUseWebViewProvider` is `undefined` when selecting it from redux store via `shouldUseWebViewProviderSelector`
Issue exists on version `2.13.2` of sdk-dapp.
`dappConfig` is not updated when using `dispatch(setDappConfig(dappConfig))`. It is always an empty object, because the `setDappConfig` action is not handled correctly in the reducer.
Instead of creating a new state at `setDappConfig`, update the same state's properties one by one. Before the state object was reassigned with a new object. This doesn't work because the state parameter is not a variable but a reference to the current state. When you reassign state, you're not changing the original state object that Redux holds, but only the local reference inside your reducer function. This is why Redux state does not get updated. …
=> [FIX] Fix `dappConfig` not saved in redux store

CHANGELOG.md, src/hooks/transactions/useSignTransactionsWithDevice.tsx
- prevent ledger Sign screen button being active before redirecting to 2FA hook
Issue exists on version `2.13` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Tm fix ledger double sign

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/services/transactions/sendTransactions.ts, src/types/transactions.types.ts
Duplicate signatures appear after signing batch transactions with web wallet
Issue exists on version `2.13.3` of sdk-dapp.
The `nonce` of each transaction to sign was updated during signing with web wallet
Prevent updating the `nonce` when signing multiple transactions with web wallet (or when the flag `preventNonceUpdate` is present).
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [FIX] Added flag to prevent updating nonce when signing transactions

CHANGELOG.md, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/services/transactions/sendTransactions.ts, src/types/transactions.types.ts
Moved nonce management within sdk-dapp. Update transaction nonce before signing only if nonce is missing
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] Improve transaction nonce update management

CHANGELOG.md, src/services/transactions/transformAndSignTransactions.ts
- new transaction was not taking into account gas limit for guarded accounts
Issue exists on version `2.13.5` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Guarded account gas Limit fix

CHANGELOG.md, src/hooks/transactions/helpers/setTransactionNonces.ts, src/hooks/transactions/helpers/useSetTransactionNonces.ts, src/hooks/transactions/tests/setTransactionNonces.test.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/services/transactions/sendTransactions.ts, src/services/transactions/transformAndSignTransactions.ts, src/types/transactions.types.ts
Incorrect nonce management on signing batch transactions with web wallet
WebWallet dApp doesn't know what the client dApp will do with the signed transactions (will send the signed transactions or not). Then, when a set of transactions arrives in the web wallet to be signed,  the web wallet takes the current account nonce from the store and computes the transactions nonces related to this. If you send the next batch (the previous one has not been executed yet) the nonce from the account is the same, then the next batch will consider the same nonce (account nonce) and will provide the transactions signed with a wrong nonce to the client dApp.
- remove unused `preventNonceUpdate`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix nonce management

CHANGELOG.md, src/hooks/transactions/batch/useSendBatchTransactions.ts
The batch transactions state is wrong after sending, causing missing tx hash on tracking
Issue exists on version `2.14.2` of sdk-dapp.
The payload has to be defined using the already signed transactions from the batch
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix batch transactions state after sending

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/components/SignStepBody.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmAmount/ConfirmAmount.tsx, src/UI/UsdValue/UsdValue.tsx
Inserting a value too large that would contain a comma would break the algorithm that calculates the USD amount of a certain token transaction.
Issue exists on version `2.14.7` of sdk-dapp.
The algorithm was using a formatted amount, used for display, instead of the raw amount that is suited for calculations.
Separated the two and only kept the displaying value for display, and the raw amount for calculations.
[x] No
[] Yes
[] No
[x] Yes
[] Unit tests
=> Updated the amount value to use the raw amount

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/SignStep.tsx
SignStep was allowing signing the same transaction twice if user was clicking too fast in signing wizard before transaction was able to load.
Issue exists on version `2.14.10` of sdk-dapp.
Transaction loading was happening slower than current step loading
Create a mapping object between transaction nonce and current step index
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix double signing

CHANGELOG.md, src/components/ProviderInitializer.tsx
- Ledger HwApp losing connection with ledger on page reload
Issue exists on version `2.14.9` of sdk-dapp.
ProviderInitializer setting ledger provider twice 
Create a local variable to prevent double setting of HWApp
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix ledger reload

CHANGELOG.md, src/apiCalls/configuration/getNetworkConfig.ts
Network config calls in tests were failing due to invalid URL origin
Issue exists on version `2.14.11` of sdk-dapp.
- validate network URL before making network config calls
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix invalid network config

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/SignStep.tsx
Signing with ledger button frozen for multiEsdtTransfer transactions
Issue exists on version `2.14.12` of sdk-dapp.
Nonce is the same at multiEsdtTransfer transactions
Create an unique identifier from `nonce` and `transactionTokenInfo.multiTxData`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix sign step transaction identifier

src/services/nativeAuth/tests/nativeAuth.test.ts
Downgrading axios to 0.24.0 on @multiversx/sdk-native-auth-client would break tests in which requests would do 404.
Issue exists on version `2.14.13` of sdk-dapp.
Create a single instance of axios in order to be used across all requests.
[x] No
[] Yes
[] Yes
[] Unit tests
=> [Testing] Axios instance

CHANGELOG.md, package.json, src/hooks/login/useLedgerLogin.ts, src/models/newTransaction.ts, yarn.lock
Ledger does not pass the initialization step on the login
Issue exists on version `2.14` of sdk-dapp.
@ledgerhq packages.
Upgrade the packages to the latest version, especially: @ledgerhq/hw-transport
"@ledgerhq/hw-transport": "6.28.4",
"@ledgerhq/hw-transport-webhid": "6.27.15",
"@ledgerhq/hw-transport-webusb": "6.27.15",
"@ledgerhq/devices": "8.0.3",
"@ledgerhq/errors": "6.12.6",
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix ledger init issue on Next.js

CHANGELOG.md, src/utils/account/getAddress.tsx, src/utils/account/getSearchParamAddress.ts, src/utils/account/index.ts, src/utils/account/tests/getSearchParamAddress.test.ts, src/wrappers/AuthenticatedRoutesWrapper/AuthenticatedRoutesWrapper.tsx
Attempting a wallet login and pressing back was causing blank screen in multiple dapps
Issue exists on version `2.15.1` of sdk-dapp.
AuthenticatedRoutesWrapper was blocking the render because of the `walletLogin` session flag.
Take account of the address parameter present in URL
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix failed wallet login attempt

CHANGELOG.md, src/hooks/websocketListener/useInitializeWebsocketConnection.tsx, src/hooks/websocketListener/useRegisterWebsocketListener.ts
Sometimes the toasts are not resolved accordingly with the response from the WS and are resolved by the fallback mechanism
Fix WS reconnect issue and the way how the batch update status is handled
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix batch transactions status update when the WS response is received

CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts, src/types/signedMessage.types.ts
Issue exists on version `2.18.4` of sdk-dapp.
Signing a message, it would not clear the URL params in the web-app.
Execute clearNavigationHistory after parsing message from url.
Added address as well in SignedMessageQueryParamsEnum in order to remove address from url when status is canceled/failed.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed issue in which signing a message, it would not clear URL

CHANGELOG.md, src/types/dappConfig.types.ts, src/wrappers/AppInitializer.tsx
NextJS double mounting because of [hydration](https://github.com/vercel/next.js/issues/36765)
Issue exists on version `2.18.5` of sdk-dapp.
Server environment differs from browser environment in AppInitializer rendering of children
Provide a custom flag when using the app with NextJS in dappConfig
[] No
[x] Yes
[x] Yes
[] Unit tests
=> Fix next js unmount

CHANGELOG.md, src/utils/account/signMessage.ts
Avoid having `undefined` in the `callbackUrl` due to the missing `callbackRoute`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix signMessage missing callbackRoute

CHANGELOG.md, src/components/ProviderInitializer/hooks/useSetLedgerProvider.ts, src/hooks/login/useExtensionLogin.ts, src/utils/account/signMessage.ts, src/utils/logout.ts, src/utils/window/addOriginToLocationPath.ts, src/utils/window/index.ts, src/utils/window/tests/addOriginToLocationPath.test.ts
Improvements to redirect URLs parsing. Added `addOriginToLocationPath` helper to parse redirect URLs. The helper checks if the URL is empty and if it has origin.
- if the URL is empty string, add the current origin;
- if the URL is a full href, leave it unchanged;
- if the URL contains current origin, leave it unchanged;
- if the URL is just a path, add current origin.
The idea is to force a page reload on logout and prevent page reloads on login (unless necessary).
[x] No
[] Yes
[x] Yes
[x] Unit tests
=> [+] Added `addOriginToLocationPath` helper to parse redirect URLs

CHANGELOG.md, src/wrappers/AppInitializer.tsx
On every render in _app (from NextJS pages directory) and in any React app that it is rerendering DappProvider, the dappConfig property creates a new reference which will trigger the intializeApp()
Issue exists on version `2.19.3` of sdk-dapp.
Rerender of DappProvider creates new reference of dappConfig.
Memoize the dappConfig and use it in order to not trigger a new app initialization.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Memoize dapp config in order to not reinitialize app

CHANGELOG.md, src/reduxStore/middlewares/loginSessionMiddleware.ts, src/reduxStore/selectors/helpers.ts, src/reduxStore/selectors/loginInfoSelectors.ts, src/wrappers/AxiosInterceptorContext/components/AxiosInterceptorContextProvider.tsx
`isLoggedIn` returns `true`, but `address` is `''`
Issue exists on version `2.19.7` of sdk-dapp.
When dispatching `logoutAction`, the `loginMethod` is cleared after the `address`, so the `isLoggedIn` selector will return `true` for a brief period, because the `loginMethod` field will not be cleared, but the `address` will.
`isLoggedIn` will depend only on the `address`. A user is logged in if the address is present and vice versa.
[] No
[x] Yes
[x] Yes
[] User testing
[x] Unit tests
=> [+] Removed `loginMethod` from the `isLoggedIn` check

CHANGELOG.md, src/components/BatchTransactionsSender/BatchTransactionsSender.ts, src/components/TransactionSender/TransactionSender.ts, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/utils/internal/optionalRedirect.ts, src/utils/logout.ts, src/utils/redirect.ts, src/wrappers/AuthenticatedRoutesWrapper/AuthenticatedRoutesWrapper.tsx
Wrong states occur after logout with a `history.pushState` redirect
Issue exists on version `2.19.8` of sdk-dapp.
React router DOM handles the routing differently than `window.history` does and incorrect states occur. Also, incorrect or partial data may occur at logout without force page reload.
Ensure redirect with page reload no matter what on logout.
[x] No
[] Yes
[x] Yes
[x] Unit tests
=> [FIX] Changed `safeRedirect` method to force page reload on logout to ensure fresh states

CHANGELOG.md, src/UI/SignTransactionsModals/components/ConfirmationScreen.tsx, src/UI/SignTransactionsModals/components/TransactionStatusToast.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx, yarn.lock
Issue exists on version `2.20.2` of sdk-dapp.
DeFi wallet would not clear the transaction when cancelled from DApps
cancelAction was removed when canceling transactions from DApps
Add back cancelAction when cancelling a transaction and remove it from transaction toast discard
[x] No
[] Yes
[x] Yes
[] Unit tests
=> clear extension bgr when cancel tx from dapp

CHANGELOG.md, package.json, src/hooks/login/useLoginService.ts, src/services/nativeAuth/helpers/getLatestBlockHash.ts, src/services/nativeAuth/nativeAuth.ts, yarn.lock
-
-
-
Add  network option when refreshing a native auth token.  Allows of refreshing a native auth token, with a new network just before network change.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add network option when refreshing a native auth token

CHANGELOG.md, src/UI/SignTransactionsModals/components/DeviceConfirmationScreen.tsx, src/hooks/login/useExtensionLogin.ts, src/hooks/login/useOperaLogin.ts, src/hooks/signMessage/useSignMessage.ts, src/hooks/transactions/useSignTransactions.tsx, src/services/transactions/sendBatchTransactions.ts, src/services/transactions/sendTransactions.ts, src/utils/clearNavigationHistory.ts, src/utils/sanitizeCallbackUrl.ts, src/utils/tests/sanitizeCallbackUrl.test.ts, src/utils/transactions/batch/generateBatchTransactionsGrouping.ts, src/utils/transactions/builtCallbackUrl.ts, src/utils/transactions/tests/builtCallbackUrl.test.ts, src/utils/window/getDefaultCallbackUrl.ts, src/utils/window/index.ts, src/utils/window/tests/getDefaultCallbackUrl.test.ts, src/web/hooks/useIdleTimer.tsx, yarn.lock
Not all information of the callbackUrl is preserved or added. `search` and `hash` may be missing.
Issue exists on version `2.21.0` of sdk-dapp.
There are places where the `hash` and `search` are discarded. In other cased when the `callbackRoute` is not specified, only the current `window.location.pathname` is added.
Create `getDefaultCallbackUrl` helper that adds the full URL without `origin` when `callbackRoute` is missing. Also, add the `search` and `hash` information where where the URL (callbackUrl) is processed.
[x] No
[] Yes
[x] Yes
[x] Unit tests
=> [+] Added `getDefaultCallbackUrl` helper

CHANGELOG.md, README.md, src/UI/webWallet/WebWalletLoginButton/WebWalletLoginButton.tsx, src/components/ProviderInitializer/ProviderInitializer.tsx, src/hooks/login/useWebWalletLogin.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/reduxStore/selectors/networkConfigSelectors.ts, src/reduxStore/slices/networkConfigSlice.ts, src/types/network.types.ts
Unable to connect to a custom web wallet provider
Add `customWalletAddress` param to networkConfig.
The `customWalletAddress` property is used to override the default `walletAddress`.
This is useful when you want to use a custom wallet provider.
It overrides the network's wallet address, including the wallet address from the custom network config specified in the `DappProvider`.
example:
```
<WebWalletLoginButton
{...otherLoginProps}
customWalletAddress="https://custom-web-wallet.com"
>
```
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Custom web wallet config

CHANGELOG.md, src/UI/extension/ExtensionLoginButton/tests/ExtensionLoginButton.test.tsx, src/UI/ledger/LedgerLoginButton/tests/LedgerLoginButton.test.tsx, src/utils/internal/optionalRedirect.ts, src/utils/logout.ts, src/utils/redirect.ts
After login, the page does not redirect correctly to the specified `callbackRoute`
Issue exists on version `2.22.1` of sdk-dapp.
Redirect is done with `window.history.pushState` instead of `window.location.assign` which seems to have undesirable side effects.
Replace `window.history.pushState` with `window.location.assign` in the `safeRedirect` helper
[x] No
[] Yes
[x] Yes
[x] Unit tests
=> [FIX] Added page reload on login redirect

CHANGELOG.md, src/UI/ledger/LedgerLoginContainer/AddressRow/AddressRow.tsx, src/UI/ledger/LedgerLoginContainer/AddressTable/AddressTable.tsx
###Feature
Add used indexes to AddressTable component
-
-
-
Allows passing an used indexes array to addressTable component. This indexes will be disabled in the component
[x] No
[] Yes
[x] Yes
[] Unit tests
=> add used indexes to addressTable component

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/SignStep.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/SignStepBody.tsx, src/UI/TransactionData/TransactionData.tsx, src/hooks/transactions/useParseMultiEsdtTransferData.ts, src/hooks/transactions/useSignMultipleTransactions.tsx, src/types/transactions.types.ts, src/utils/transactions/getUnHighlightedDataFieldParts.ts, src/utils/transactions/index.ts, src/utils/transactions/parseMultiEsdtTransferData.ts, src/utils/transactions/tests/getUnHighlightedDataFieldParts.test.ts, src/utils/transactions/tests/parseMultiEsdtTransferData.test.ts
Cannot sign a `MultiESDTNFTTransfer` and highlight is not showing the transaction data correctly.
Issue exists on version `2.22.5` of sdk-dapp. Go to this [sign hook](https://devnet-wallet.multiversx.com/hook/sign?nonce%5B0%5D=786&value%5B0%5D=0&receiver%5B0%5D=erd1wh9c0sjr2xn8hzf02lwwcr4jk2s84tat9ud2kaq6zr7xzpvl9l5q8awmex&sender%5B0%5D=erd1wh9c0sjr2xn8hzf02lwwcr4jk2s84tat9ud2kaq6zr7xzpvl9l5q8awmex&gasPrice%5B0%5D=1000000000&gasLimit%5B0%5D=7000000&data%5B0%5D=MultiESDTNFTTransfer%40000000000000000005006704c51b25a956ddbc643189ba7945b413890d4f0fd6%4002%40444d452d626465326238%4001%4001%40444d452d626465326238%4001%4001%406e6674446973747269627574696f6e%40ee62513ef30aede25b3366b6e3219ee18084026f36d6105299ee9963b1338f09%40ee62513ef30aede25b3366b6e3219ee18084026f36d6105299ee9963b1338f09&chainID%5 …
=> Fixed `MultiESDTNFTTransfer` data field highlight and signing

CHANGELOG.md, src/UI/index.ts, src/UI/webWallet/XaliasLoginButton/XaliasLoginButton.tsx, src/UI/webWallet/XaliasLoginButton/index.tsx, src/constants/dataTestIds.enum.ts, src/constants/network.ts, src/hooks/login/index.ts, src/hooks/login/useXaliasLogin.ts, src/reduxStore/selectors/networkConfigSelectors.ts, src/types/network.types.ts
Support xAlias login with specific methods
Issue exists on version `2.22.5` of sdk-dapp.
Connection to xAlias was done trough customWebWalletAddress
Create network entry and specific login button and hook
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Implement xAlias login button and hook

CHANGELOG.md, src/UI/UsdValue/UsdValue.tsx, src/utils/logout.ts, yarn.lock
Logout is not working on wallet.
Issue exists on version `2.24.1` of sdk-dapp.
Wallet provider is always present and the `provider.logout` is called no matter what, causing the wallet to constantly reload and navigate to logout hook.
Avoid calling logout actions if not logged in.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed logout for wallet provider

CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts, src/reduxStore/slices/signedMessageInfoSlice.ts
Signing a message with web wallet provider it will override the signedSession object and it will remove the message.
Issue exists on version `2.24.4` of sdk-dapp.
Overriding entire signedSession object.
Update only the properties that needs to be updated.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix issue in which signing a message with wallet would override message

CHANGELOG.md, src/utils/logout.ts, yarn.lock
If the the `callbackURL` from the `logout()` function is the same as the pathname where the `logout()` was triggered, we might end up in infinite redirects/reloads. (logout path -> logout() -> logout path -> logout()).
Issue exists on version `2.24.4` of sdk-dapp.
No mechanism to prevent redirect to current URL.
Check if the pathname where `logout()` was triggered is the same as the `callbackUrl` of the `logout()` function and prevent redirect in that case.
- Execute the logout function flow regardless if logged in or not;
- Removed unused/redundant code in `logout` function for the `isWalletProvider` scenario.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent redirect on logout if `callbackURL` is the current URL

CHANGELOG.md, src/utils/logout.ts, src/utils/window/tests/addOriginToLocationPath.test.ts
There are cases when during the `logout` function the provider is `wallet` and not initialised, but it triggers logout and redirect to web wallet logout hook.
Issue exists on version `2.25.0` of sdk-dapp.
Prevent `provider.logout()` if the provider is not initialised and not logged in.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent provider logout when not logged in or initialized

CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts
Sign message callbackRoute needs entire URL as callbackRoute, which differs to callbackUrl defined for signing transactions 
Issue exists on version `2.25.2` of sdk-dapp.
Current implementaiton:
`const callbackUrl = new URL(callbackRoute)` 
Changed message signing url to use `addOriginToLocationPath` in order to build the URL.
All previous callbackRoutes which used the entire URL as callback will no longer work.
The new callbackRoute should be something like: `/dashboard`
[] No
[x] Yes
[x] Yes
[] Unit tests
=> ⚠️ Update sign message callbackRoute

CHANGELOG.md, src/hooks/signMessage/useSignMessage.ts
Cancelling a sign message does not display a toast with a specified message.
Issue exists on version `2.25.2` of sdk-dapp.
Sign message URL params does not contain `signSession` in order for `useParseSignedTransactions` to be able to intercept and display the message.
Instead of adding a new param for the URL, use directly `setSignTransactionsCancelMessage` in order to display the `errorMessage`.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Toast for cancel sign message does not show

CHANGELOG.md, src/utils/logout.ts
Calling `logout` causes the app the crash if net reloaded at the end.
Issue exists on version `2.25.2` of sdk-dapp.
Dispatch logout action should also be called only if logged in or if the provider is initialised, simnilar to the provider logout call. Also, it should be called right before the provider logout function call.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent logout action when not logged in or provider not initialized

CHANGELOG.md, package.json, src/utils/logout.ts
Logout attempts within sdk-dapp do no redirect to the unlock page of the web wallet.
Issue exists on version `2.26.3` of sdk-dapp.
If the provider is not initialised, but it is of type wallet then the redirects will fail, becase the `preventRedirects` si set to `true` and the provider itself will no longer make redirects within, as it it not initialised.
Set `preventRedirects` to `true` only if the provider is both initialised and of wallet type.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent redirects on logout if the provider is both of wallet type and initialised

CHANGELOG.md, src/services/nativeAuth/helpers/loginWithNativeAuthToken.ts, yarn.lock
The web wallet logouts and reloads the page when trying to login via webview.
Issue exists on version `2.26.6` of sdk-dapp.
The logout action is triggered from sdk-dapp and the `shouldAttemptRelogin` parameter is set to `false`, because the `webviewToken` is missing. This is caused by the logout actions dispatch triggered before the `nativeAuth` login action.
Prevent sending the logout action before initiating the login action within the webview login.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent logout before webview login

CHANGELOG.md, package.json, src/hooks/transactions/helpers/checkIsValidSender.ts
Need to check for multiple valid addresses
Issue exists on version `2.28.1` of sdk-dapp.
Support multisig contract check
Extend `checkIsValidSender` with array or string argument
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Extend `checkIsValidSender` with array or string argument

.github/workflows/changelog.yml, CHANGELOG.md, src/hooks/login/useWalletConnectV2Login.ts
Walletconnect conflict with external provider if walletconnect method is not chosen, when all methods are shown including QR code.
Issue exists on version `2.28.3` of sdk-dapp.
Walletconnect account provider is set when showing QR code. 
Delay setting `accountProvider` on `handleLogin`
Add changelog.yml to workflows
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix walletconnect set account provider

CHANGELOG.md, src/hooks/login/useLoginService.ts
Setting login token makes reload lose existing information
Issue exists on version `2.28.3` of sdk-dapp.
Wrong rewrite of loginToken data in redux
```
dispatch(
setTokenLogin({
...tokenLogin, // --> ADDED 
loginToken,
...(apiAddress ? { nativeAuthConfig: configuration } : {})
})
);
```
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed setting `loginToken` in `useLoginService` losing previous state

CHANGELOG.md, src/utils/logout.ts
Logging out from a dapp creates infinite loop between dapp logout route and web wallet
Issue exists on version `2.28.4` of sdk-dapp.
1. set native auth token expirySeconds to 15
2. login with web wallet
3. wait for nativeAuth token to expire
4. sdk-dapp auto-triggers logout and goes to web wallet provider to logout there. CallbackUrl is set to local dapp logout route
5. logout is called again in sdk-dapp and the process repeats
On the second logout sdk dapp store should have been cleared but setTimeout with no arguments is not enough and Chrome redirect prevents full JS execution
Delay web wallet navigation by 500ms to allow clearing sdk-dapp store
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix logout web wallet infinite loop

CHANGELOG.md, src/utils/toasts/customToastsActions.ts
In some cases if there is a mismatch between dapp and sdk-dapp redux store, payload cannot be destructured
Issue exists on version `2.28.5` of sdk-dapp.
Use optional chaining
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix possibly undefined payload

CHANGELOG.md, src/UI/walletConnect/WalletConnectLoginContainer/WalletConnectLoginContainer.tsx, src/UI/walletConnect/WalletConnectLoginContainer/WalletConnectLoginContent/WalletConnectLoginContent.tsx, src/hooks/login/useExtensionLogin.ts, src/hooks/login/useWalletConnectV2Login.ts
Cannot login with wallet connect and other providers, if the `WalletConnectLoginContainer` is used as standalone component without the modal in the login/unlock page.
Issue exists on version `2.28.5` of sdk-dapp.
Wallet connect is initialising and logging in automatically on component init if used as standalone component, because it is no longer destroyed like the modal is.
Prevent auto-login on component init.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed wallet connect breaks login with other providers

CHANGELOG.md, package.json, src/hooks/transactions/useParseSignedTransactions.tsx, src/types/dappConfig.types.ts, yarn.lock
Allow optionally fetching `walletURL` on application load time 
Issue exists on version `2.28.6` of sdk-dapp.
If a dApp loads and URL is cleared or dapp navigates to another URL so that useParseSignedTransactions gets loaded later, the search params are cleared and new `WalletProvider().getTransactionsFromWalletUrl` is unable to fetch the transactions
Optionally add to `DappConfigType` `shouldFetchWalletUrlOnLoad` option that saves the search param on application load time
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add option to fetch wallet url on load

CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx, src/components/ProviderInitializer/helpers/getModifiedLoginToken.ts, src/components/ProviderInitializer/helpers/index.ts, src/components/ProviderInitializer/helpers/processMultisigAccount.ts, src/components/ProviderInitializer/helpers/tests/getModifiedLoginToken.test.ts, src/hooks/login/useCrossWindowLogin.ts, yarn.lock
Add support for impersonate in nativeAuth token
Issue exists on version `2.28.7` of sdk-dapp.
Allow some addresses to impersonate trough nativeAuth token by integrating `impersonate` key in `extraInfo`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add support for nativeAuth impersonate

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/SignStep.tsx, src/hooks/transactions/helpers/getAreAllTransactionsSignedByGuardian.ts, src/hooks/transactions/useSignMultipleTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/types/transactions.types.ts
Unable to sign multiple guarded ledger transactions
Issue exists on version `2.28.7-alpha.21` of sdk-dapp.
Ledger flow was reset and sigining was called again at the end
Change `useSignMultipleTransactions` to make `sign` return a promise and wait for signing & if all have been signed by guardian exit the flow with `onTransactionsSignSuccess`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix ledger guardian signing

CHANGELOG.md, package.json, src/utils/decoders/base64Utils.ts, src/utils/decoders/tests/base64Utils.test.ts
Transaction data string `fd` is treated as base64 encoded string and transformed into `}`
Issue exists on version `2.28.7` of sdk-dapp.
`atob()` and `Buffer.from()` of `fd` are equal, so, the utility function `isStringBase64()` returns `true` which forces an additional encoding of the transaction data field.
Remove the check for the equality of `atob()` and `Buffer.from()` as a condition for base64 encoding.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed base64 utils encoding check and conversion

CHANGELOG.md, src/providers/accountProvider.ts, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts, src/wrappers/DappProvider/DappProvider.tsx
The experimental webview provider doesn't notify the parent when is loaded.
Issue exists on version `2.29.0-beta.0` of sdk-dapp.
Wrong implementation of the init() function
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix experimental webview provider initialization

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, src/reduxStore/selectors/accountInfoSelectors.ts, src/reduxStore/slices/accountInfoSlice.ts
The `address` from `useGetAccountInfo` hook is different than the `address` from `useGetAccount` hook.
Issue exists on version `2.29.0-beta.3` of sdk-dapp.
In case the getAccount fails, the `address` from `loginInfoSlice` is not reset.
Return the account address in the `accountInfoSelector` as the main address and clear the `address` and `publicKey` from `loginInfloSlice` in case the `getAccount` fails.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed different address than account address in account info

CHANGELOG.md, src/utils/logout.ts
"Failed to construct 'URL': Invalid URL"
Issue exists on version `2.29.0-beta.5` of sdk-dapp.
The URL coming from the wallet should be decoded.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix web wallet URL construction on logout action

CHANGELOG.md, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts
Incorrect response handling for signTransactions and signMessage actions
Issue exists on version `2.29.0-beta.9` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: "Cancel response" handling for the signTransactions and signMessage actions

CHANGELOG.md, package.json, yarn.lock
protobufjs is mandatory because was moved in peerDeps in the latest version of the sdk-core
Issue exists on version `2.29.0-beta.10` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add protobufjs as dependency

CHANGELOG.md, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts
Login with web-wallet: The user is unable to sign other transactions or messages if previously cancelled an action.
Issue exists on version `2.29.0-beta.15` of sdk-dapp.
Add misssing cancelAction call on signTransactions and signMessage methods
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: fix cancel actions

CHANGELOG.md, package.json, src/wrappers/DappProvider/CustomComponents.tsx
Allow configuring LogoutListener
Issue exists on version `2.29.0-beta.16` of sdk-dapp.
Logout from a dapp using web wallet may trigger a logout action from same account logged into a different dapp
Allow LogoutListener to be customized inside CustomComponents
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix triggering logout from other dApps

CHANGELOG.md, package.json, src/utils/logout.ts
The wallet automatically logs out (with redirect to different host) and replies with cancelled when logged in with a locked or unavailable ledger device.
Issue exists on version `2.29.0-beta.18` of sdk-dapp.
When ledger is busy and we are logged in, the providerType appears as wallet and ledger initialisation fails. This causes the logout to be triggered and a redirect to the wallet URL, without trying to re-login.
Prevent wallet redirects within the wallet provider `logout` method if the provider is not initialised
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed cross-window ledger re-login when device is locked

CHANGELOG.md, src/reduxStore/slices/transactionsSlice.ts
The transactions toast status remains in "pending" state when multiple transactions are tracked and some fail
Issue exists on version `2.29.0-beta.24` of sdk-dapp.
Wrong status computation
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix transactions toast status in case of some failed transactions

CHANGELOG.md, package.json, src/hooks/transactions/useSignMultipleTransactions.tsx, src/hooks/transactions/useSignTransactions.tsx
During transactions validation, the `getAccount` method is called multiple times, causes performance issues.
Issue exists on version `2.29.0` of sdk-dapp.
Get account by sender address only once in the beginning of the hook and reuse it withitn the validation steps
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Changed signTransactions to prevent re-fetching of account during validation

CHANGELOG.md, src/hooks/transactions/useSignTransactionsCommonData.tsx
Missing trigger of the cancel action when the user aborts signing transactions
Issue exists on version `2.29.0-beta.27` of sdk-dapp.
Missing implementation
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: fix cancel action on sign transactions flow

src/hooks/transactions/batch/tracker/useUpdateBatch.ts, src/hooks/transactions/useCheckTransactionStatus/checkBatch.ts, src/hooks/transactions/useCheckTransactionStatus/manageFailedTransactions.ts, src/reduxStore/slices/transactionsSlice.ts
Sync signed transactions fields with the corresponding fields from the API
Issue exists on version `2.29.0-beta.29` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Sync signed transactions fields with the corresponding fields from the API

CHANGELOG.md, executeBuildCommand.js, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts
For the mobile webview, a message of type string is necessary. Therefore, we must specifically manage the webview message related to requests and responses.
Issue exists on version `2.29.2` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: Enhance mobile webview compatibility to provide comprehensive support.

CHANGELOG.md, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts, src/providers/experimentalWebViewProvider/helpers/getSafeDocument.ts, src/providers/experimentalWebViewProvider/helpers/getSafeWindow.ts, src/providers/experimentalWebViewProvider/helpers/isMobileWebview.ts, src/providers/experimentalWebViewProvider/helpers/webviewProviderEventHandler.ts
Mobile webview supports only string messages. We have to deserialize the event data in order to extract the fields from the response.
Issue exists on version `2.30.0` of sdk-dapp.
Missing deserialization
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: fix mobile response

CHANGELOG.md, package.json, src/UI/ledger/LedgerLoginContainer/AddressRow/AddressRow.tsx, src/UI/ledger/LedgerLoginContainer/AddressRow/addressRowStyles.scss
Unable to click on the address table anywhere on the row other than the actual input dot.
Issue exists on version `2.30.1` of sdk-dapp.
The click event was scoped exclusively to the input instead of the entire row.
Kept the click event on the input due to state handling limitations of React for inputs, but also applied it to the entire row.
[x] No
[] Yes
[x] Yes
[] No
[] Unit tests
=> Fixed address table select area

CHANGELOG.md, package.json, yarn.lock
Lit in sdk-web-wallet-cross-window-provider breaks development build of dApps
Issue exists on version `2.31.4` of sdk-dapp.
Uncaught SyntaxError: Identifier 'global' has already been declared
To be investigated in a future release
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Downgrade sdk-web-wallet-cross-window-provider to non-lit environment

CHANGELOG.md, src/wrappers/AuthenticatedRoutesWrapper/AuthenticatedRoutesWrapper.tsx
Cannot login with `accessToken` in URL (Webview login)
Issue exists on version `2.31.6` of sdk-dapp.
`AuthenticatedRoutesWrapper` does not check for `accessToken` and redirects to `unlockRoute` regardless. Webview login with `accessToken` is a bit laggy.
Added an additional check to the `shouldRedirect` flag, using `getWebviewToken` method.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed `AuthenticatedRoutesWrapper` redirects to unlock route during webview login

CHANGELOG.md, package.json, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts
Send custom message method was not implemented on webview provider
Issue exists on version `2.32.3` of sdk-dapp.
Implement send custom request method
[x] No
[] Yes
[x] Yes
[] Unit tests
=> fix webview custom message

CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx
Provider not initialized in custom environment with chain ID other than `1 / D / T`
Remove `getEnvironmentForChainId` check in `ProviderInitializer` 
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix custom environment

CHANGELOG.md, src/hooks/login/useWalletConnectV2Login.ts, src/utils/waitForChainID.ts
- infinite loading when using custom network config;
- redirect to wallet address login hook after logout when using custom network config.
- Go to web wallet unlock page;
- Add a custom network (https://mx-api-sov-ovh.elrond.ro)
- Login and then logout
Actual result: Infinite loading on wallet connect and user is redirected to https://wallet.voyager1.dev/hook/login
Expected result: wallet connect is loaded successfully and the user can relogin into the wallet without any other redirects
- invalid chainId is set when using different chain ID then mainnet, testnet, and devnet;
- wallet provider is set instead of wallet connect provider. Wallet provider attempts login.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed walletconnect infinite loading and wallet redirect when using custom network config

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, src/reduxStore/slices/accountInfoSlice.ts
User may be logged in with address different than the one from nativeAuth token on store rehydrate
Ensure the address from the nativeAuth token is the same with the one from the account in store
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed logged in address is different than address from nativeAuth token

CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx
Impersonate no longer works on web wallet
Impersonated address is changed to the previous address, because the nativeAuth token is not changed
Skip nativeAuth token address check durning impersonate process
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Removed address check for impersonate action in `ProviderInitializer`

CHANGELOG.md, src/utils/transactions/parseMultiEsdtTransferData.ts, src/utils/transactions/tests/parseMultiEsdtTransferData.test.ts
There is an infinite loop in web wallet when signing this transaction:
`
let transaction: IPlainTransactionObject = {
chainID: 'D',
receiver:
'erd1qqqqqqqqqqqqqpgqd9z7versxw2pjywsar3mshy8ddhvgjwmzeushy7m7s',
sender: 'erd12n774mvuzx5d5fulnx9ykmgykgqtmw8pvc58fzzcyxv96r9sq67sy6m59f',
data: 'MultiESDTNFTTransfer@000000000000000005006945e6647033941911d0e8e3b85c876b6ec449db1679@55544b2d353463323862@@091d@55544b4641524d2d653539363331@02@04b4a8335ecc4a780000@55544b4641524d2d653539363331@03@a968163f0a57b4000000@7374616b654661726d',
version: 1,
value: '0',
nonce: account.nonce,
gasPrice: GAS_PRICE,
gasLimit: 25000000
};
`
In `parseMultiEsdtTransferData`, the `encodedTxCount` is `55544b2d353463323862`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed infinite loop in `parseMultiEsdtTransferData`

CHANGELOG.md, src/reduxStore/slices/networkConfigSlice.ts
Transactions signing fail on dapp refresh.
- Go to Devnet Wallet (on firefox);
- Login with xPortal or Extension;
- Refresh;
- Send a transaction.
Actual Result: Transaction cancelled error appears
Expected Result: Transactions are signed and processing
`chainID` is set to `-1` by default. This causes the chainID check to pass as truthy in `waitForChainID` function and return an incorrect value.
Furthermore, the returned chainID will be different than the chainID of the signed transactions, so, those transactions will fail.
Make the `chainID` `''` by default.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Updated default chainID to empty string instead of `-1`

CHANGELOG.md, src/wrappers/AppInitializer.tsx, src/wrappers/DappProvider/DappProvider.tsx
sdk-dapp enforces a knwon environment
Issue exists on version `2.33.3` of sdk-dapp.
There were only strict environments until sovereign shards
Allow custom string as environment and get config from url
Improve DappProvidere type imports
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Allow custom environment as string

CHANGELOG.md, src/types/network.types.ts, src/wrappers/AppInitializer.tsx
No walletconnect default settings for custom network
Issue exists on version `2.33.4` of sdk-dapp.
- add 'wss://relay.walletconnect.com' to fallbackConfig
- fixed apiTimeout type to string | number
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix walletconnect settings for custom network

CHANGELOG.md, src/hooks/transactions/useGetPollingInterval.ts
Sovereign chains have one round, so, no need to add `CROSS_SHARD_ROUNDS` to the polling interval calculations.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Removed cross shard rounds from polling interval calculations

CHANGELOG.md, package.json, src/hooks/login/useWebViewLogin.ts, src/reduxStore/slices/loginInfoSlice.ts, src/services/nativeAuth/helpers/loginWithNativeAuthToken.ts, src/utils/account/getAccessTokenFromSearchParams.ts, src/utils/account/getWebviewToken.ts, src/wrappers/DappProvider/DappProvider.tsx
`getWeviewToken` function returns wrong result in some contexts outside of `webview` provider
Issue exists on version `2.36.0` of sdk-dapp.
Fix the `getWebviewToken` function and still keep the login functionality on `webview` untouched
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix Webview login and logout action

CHANGELOG.md, src/services/transactions/signTransactions.ts, src/types/transactions.types.ts
If a user wants to sign a transaction and has no balalance, signing does not work
Issue exists on version `2.36.1` of sdk-dapp.
Transactions cannot be signed if main balance is 0
Remove check for main balance over min gas limit
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Remove insufficient funds check

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/types/transactions.types.ts
Added ability to skip updating transaction nonces
Issue exists on version `2.36.3` of sdk-dapp.
If a soveregin shard has the same Chain ID as a testnet from fallbackNetworkConfigurations, nonces may be wrongly fetched from that network
Allow skipping this mechanism
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Added ability to skip updating transaction nonces

package.json, yarn.lock
When a cross-window login is triggered and aborted then a new login with metamask proxy provider is initiated, the MetamaskProxyProvider instance is overridden by the CrossWindowProvider
Issue exists on version `2.38.3` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix MetamaskProxy Provider singleton instance

CHANGELOG.md, src/UI/SignTransactionsModals/SignTransactionsModals.tsx, src/UI/SignTransactionsModals/SignWithMetamaskModal/SignWithMetamaskModal.tsx
Display transactions signed by metamask one by one
Metamask does not offer transaction details
Use sdk-dapp sign screens same as for ledger
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Make metamask sign with sign screens

CHANGELOG.md, src/apiCalls/tokens/getPersistedToken.ts, src/apiCalls/tokens/tokenDataStorage.ts, src/apiCalls/transactions/getTransactionsByHashes.ts, src/hooks/transactions/useGetTokenDetails.tsx, yarn.lock
When signing multiple transactions, same token call is made multiple times thus delaying the display of sign screens
Issue exists on version `2.38.7` of sdk-dapp.
No caching
Created `getPersistedToken` helper with injectable storage by using `setTokenDataStorage`
Use `TRANSACTIONS_ENDPOINT` in `src/apiCalls/transactions/getTransactionsByHashes.ts`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Cached token

CHANGELOG.md, src/hooks/websocketListener/useInitializeWebsocketConnection.tsx
After logout and login to another account/address, the websocket event no longer works.
Websocket connection still exists for the previous logged int account.
Close connection on logout and reconnect only when logged in.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed websocket connection is not closed on logout

CHANGELOG.md, package.json, src/utils/account/addressIsValid.ts
When checking for valid address we check if it statrs with "erd" this does not allow other HRP's
Issue exists on version `2.40.6` of sdk-dapp.
Hardcoded "erd" check 
Remove the hardcoded "erd" since converting the string to Address object should be sufficient
[x] No
[] Yes
[x] Yes
[] Unit tests
=> remove starts with erd check for valid addresses

CHANGELOG.md, src/wrappers/AxiosInterceptorContext/components/AxiosInterceptor.tsx
Dapp is receiving the native auth token before the interceptor is set
When the native token is set in `useAxiosInterceptorContext`, API call from dapp is triggered before interceptor is set and leads to a concurrency issue
Remove native token useEffect dependency for injecting the interceptor
=> Fix axios interceptors concurrency

CHANGELOG.md, src/hooks/login/helpers/clearInitiatedLogins.ts, src/hooks/login/useCrossWindowLogin.ts, src/hooks/login/useIframeLogin.ts
When logging into another with Web Wallet cross window multiple tabs where opened if another wallet tab is already open
Open a wallet tab and in parallel open a dapp and try login with web wallet cross window
Issue exists on version 3.0.8 of sdk-dapp.
When the provider is already initialised the clearInitiatedLogins tries to close all other logins providers sessions instead of clearing the cross window session
Change clearInitiatedLogins to only clear current login method provider session
No
=> Fix clear initiated login

CHANGELOG.md, src/utils/validation/stringIsFloat.ts, src/utils/validation/tests/stringIsFloat.test.ts
Checking if a string is a floating number would wrongfully return `false` for amounts with many decimals points, such as `0.0000000011231723871623178236182376123`, that exceeds the default decimal places of `BigNumber.js` set at `20`. 
Issue exists on version `3.0.11` of `mx-sdk-dapp`.
Added a `BigNumber.set` method to set the decimal places to whatever the decimals' length is. Otherwise, keep it to the default one.
=> Fixed "stringIsFloat" issue for huge decimal numbers

CHANGELOG.md, src/utils/validation/stringIsFloat.ts
The `BigNumber` configuration was not properly cleaned up in the `stringIsFloat` helper function, thus overwriting the configuration in other helper functions too, creating a race condition.
Issue exists on version `3.0.12` of sdk-dapp.
The cause was the `BigNumber.set` method called globally in the `stringIsFloat` helper function.
Create a clone of the `BigNumber` instance and scope it locally, and only change the settings at a local function level.
=> Fixed BigNumber.js scoping

CHANGELOG.md, src/constants/network.ts
- Updated default metamaskSnapWalletAddress
=> Updated default metamaskSnapWalletAddress

.github/workflows/npm-publish.yml, .github/workflows/pre-merge-unit-tests.yml, CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx
The network config is fetched from `/dapp/config` regardless. We need to fetch the config only if the `chainId` is missing or if we need the `roundDuration`. The `roundDuration` is used in (sovereign) chains that do not have websocket and rely on regular polling intervals to refresh the data.
=> Updated get network config from API logic

CHANGELOG.md, package.json, yarn.lock
Incorrect dApp compatibility check triggered by the webview provider v2.0.2
Issue exists on version `3.1.0` of sdk-dapp.
=> Fix dApp compatibility check (webview provider)

CHANGELOG.md, src/UI/Pagination/Pagination.tsx, src/UI/ledger/LedgerLoginContainer/AddressTable/AddressTable.tsx
Added support for the `AddressTable` and pagination component to support a `count` parameter in order to create a pagination with a fixed given amount of supported items and pages. Feature doesn't exist on version `3.1.1` of `sdk-dapp`.
=> Address Table Pagination Count Support

CHANGELOG.md, src/utils/logout.ts
Automatic reply with cancelled is triggered when Ledger is disconncted, but previously logged in.
- Login in a DApp via web wallet cross window with ledger;
- Disconnect Ledger device;
- Try to sign a transaction
- Automatic Transaction cancelled is triggered
When the provider is not initialised, but the address is present in sdk-dapp, an internal logout is triggered, which makes the page redirect to unlockRoute. Page redirects or reloads cause the cross-window tab to close and trigger automatic transaction cancel.
Prevent redirects when we are in cross window and the redirect origin is the same as the current origin.
=> Fixed cross window page reload on internal logout

CHANGELOG.md, package.json, yarn.lock
Some transactions are not working on ledger stax
Swap EGLD -> HTM
TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6e02)
Swap WEGLD -> HTM
index-kBwkE79w.js:384 tokenDataStorage unable to parse SyntaxError: "undefined" is not valid JSON
Upgrade ledger-hq
=> Upgrade ledger-hq to alpha

CHANGELOG.md, package.json, src/wrappers/AuthenticatedRoutesWrapper/AuthenticatedRoutesWrapper.tsx, yarn.lock
Dapps load twice on page refresh
Refresh the page and watch the network tab
Issue exists on version `3.1.6` of sdk-dapp.
Authenticated routes wrapper switches between rendering null and rendering children
Stop the switch if account data is already available
Revert ledger-hq alpha version
=> Fix double rendering

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmReceiver/ConfirmReceiver.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmReceiver/confirmReceiverStyles.scss
Add the possibility to optionally not trim the receiver inside the `ConfirmReceiver` components. This is useful for the situations where you don't want to show a trimmed address in case of sending to a scam address by mistake.
Feature doesn't exist on version `3.2.0` of `sdk-dapp`.
=> Added Optional Receiver Trimming Option

CHANGELOG.md, package.json, src/hooks/login/helpers/clearInitiatedLogins.ts, src/hooks/login/useCrossWindowLogin.ts, src/hooks/login/useWalletConnectV2Login.ts, yarn.lock
After a failed/cancelled login attempt with cross window provider, wallet connect QR code does not longer initialize and the cross window tab opens.
1. Refresh xexchange
2. Click connect -> open sidepanel
3. Click Web wallet -> new tab opens
4. Close the wallet tab
5. Close the side panel
6. Open the side panel again
Result: QR code does not load and new wallet tab always opens, although web wallet login button was not clicked
1. Wallet connect `isInitialized` flag check does not check for the provider type;
2. `CrosswindowProvider` is set globally after login attempt, event when it fails/cancelled;
3. `CrosswindowProvider` is not disposed/reset after failed login attempt;
4. `CrossWindowProvider` `dispose` method does not reset correctly …
=> Fixed walletconnect init fails after cross window login attempt

CHANGELOG.md, src/constants/extension.constants.ts
Metamask links point to wrong web store extensions
The Chrome Web Store has migrated from chrome.google.com/webstore to chromewebstore.google.com. This commit updates the Metamask extension link to use the new domain.
=> Fix: update metamask addon link to use new Chrome Web Store domain

CHANGELOG.md, package.json, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmFee/ConfirmFee.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmFee/components/GasDetails/GasDetails.tsx, src/types/network.types.ts
In some cases, choosing fast price will output the same minimal price. Solution is to only show price editing options if the options increase the default transaction price.
Tried to sign a transaction with a really small gas limit like 50,000
Recommend gas price function outputs minimal gas price
Compare minimal price with the existing initial gas price and only show the radius if it is higher
Upgrade to gasStationMetadata
=> Conditional price radios

CHANGELOG.md, package.json, src/utils/account/addressIsValid.ts
- Updated address validation, removed length check due to custom HRPs
- Use isValid from sdk-js
=> Update Address Validation

CHANGELOG.md, src/UI/TransactionData/TransactionDataStyles.scss
Styles were broken for the data field decode options dropdown. It was floating to the right of whatever element it first found with `position: relative`. Issue exists on `v3.3.1` of `sdk-dapp`.
=> Fixed floating data field decode dropdown

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, src/hooks/login/useCrossWindowLogin.ts, src/models/newTransaction.ts
Using a custom `walletAddress` in `useCrossWindowLogin` does not persist for signing
login like
```
const [onInitiateDevnetLogin] = useCrossWindowLogin({
callbackRoute: RouteNamesEnum.dashboard,
nativeAuth,
onLoginRedirect: () => {
navigate(RouteNamesEnum.dashboard);
},
walletAddress: 'https://devnet-wallet.multiversx.com'
});
```
does not persist the used `walletAddress`
not saved to store
save in existing `customWalletAddress` that gets removed at logout
Fixed `relayerAddress` econding
=> Support two cross-window wallets

CHANGELOG.md, src/utils/logout.ts
There was an error when calling logout: 'Unable to perform logout with options. Provider is not initialized'
Navigate to https://devnet-wallet.multiversx.com/logout multiple times (when logged in or not)
The logout logic doesn't check if the provider is initialized before calling `provider.logout()`, leading to errors when trying to logout with an uninitialized provider.
Refactor logout logic to prevent calling `provider.logout()` if the provider is not initialized, ensuring safer logout behavior.
=> Prevent calling `provider.logout()` if not initialized

CHANGELOG.md, src/core/managers/UnlockPanelManager/UnlockPanelManager.ts, src/core/managers/UnlockPanelManager/UnlockPanelManager.types.ts
Add `closeCallback` support to `UnlockPanelManager` to allow handling redirection or UI cleanup when login is not performed.
=> Add closeCallback in UnlockPanelManager

CHANGELOG.md, package.json, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts, src/providers/experimentalWebViewProvider/useInitiateExperimentalWebviewLogin.ts, src/reduxStore/middlewares/loginSessionMiddleware.ts, src/utils/logout.ts, src/wrappers/DappProvider/DappProvider.tsx
Hub webview logout not working
Login to hub and press logout from dApp => no logout action is performed
1. The finally clause was causing a redirect before webview provider was able to send the logout request
2. Clearing the storage was not working on logout from webview
1. Added condition to skip page reload on logout with extra provider
2. Clear the storage in provider logout by calling `persistor.purge()`
lint
=> Fix webview logout

.github/workflows/pre-merge-unit-tests.yml, CHANGELOG.md, package.json, src/services/transactions/__tests__/transformAndSignTransactions.test.ts, src/services/transactions/signTransactions.ts, src/services/transactions/transformAndSignTransactions.ts, src/types/transactions.types.ts
Added support for relayer and relayerSignature in transactions to enable relayed transaction functionality.
Added support for relayer and relayerSignature in the transaction transformation process:
- Added relayer and relayerSignature fields in the transaction types
- Updated `transformAndSignTransactions` to handle relayer information
- Added relayer support in the `newTransaction` function
- Added test coverage for relayer functionality
=> Added `relayer` and `relayerSignature` in the transaction in `transformAndSignTransactions`

CHANGELOG.md, package.json, src/types/index.ts, src/types/suspiciousLink.types.ts, src/utils/transactions/getScamFlag.ts, yarn.lock
Add utility for scam/suspicious content detection in asset messages, with supporting types and dependency.
There was no utility to programmatically detect and flag suspicious or scam content (such as links, NSFW, or scam info) in asset messages. Types for this logic were also missing, and the `linkifyjs` dependency was not present.
- Added `getScamFlag.ts` utility in `src/utils/transactions/` to check for suspicious content in asset messages.
- Added supporting types in `src/types/suspiciousLink.types.ts`.
- Added `linkifyjs` as a dependency in `package.json` for link detection in text.
N/A
=> Add utility for scam/suspicious content detection in asset messages, with supporting types and dependency.

CHANGELOG.md, src/providers/ProviderFactory.ts
- Login with wallet does not work due to wrong check of type.
Issue exists on version `5.0.0-alpha.12` of sdk-dapp.
- invalid check of type in DappProvider
- Update type check
=> Fix issue with wallet login

CHANGELOG.md, package.json, src/methods/initApp/initApp.ts, src/services/nativeAuth/methods/getDefaultNativeAuthConfig.ts, src/utils/account/index.ts, src/utils/account/refreshNativeAuthTokenLogin.ts, src/utils/window/getWindowLocation.ts, yarn.lock
- Update the default native auth config logic to accept an object as config.
- Add support for `allowedProviders` as a list of strings.
- Update to `@multiversx/sdk-dapp-ui@0.0.9`.
- Moved refreshNativeAuthTokenLogin from core to utils/account 
- The previous implementation of `getDefaultNativeAuthConfig` only accepted a string (`apiAddress`), limiting flexibility.
- `allowedProviders` previously required a more complex structure, making it harder to specify allowed providers simply.
- Changed `getDefaultNativeAuthConfig` to accept an object, allowing for more flexible configuration (origin, apiAddress, expirySeconds, etc).
- Updated `allowedProviders` to accept a list of provider type strings, simplifying usage and configuration.
- Upgraded `@multiversx/sdk-dapp-ui` to version `0.0.9`.
- …
=> Default native auth config

CHANGELOG.md, src/methods/initApp/initApp.ts
initApp can be called twice while firts call does not finis
call initApp in useEffect
Add a flag to prevent execution while init is in progress
=> Fixed init app double init

CHANGELOG.md, src/providers/DappProvider/helpers/login/login.ts, src/providers/types/providerFactory.types.ts
- logging in from hub has invalid signature
- login to dApp from hub
Issue exists on version `5.0.4` of sdk-dapp.
- nativeAuthToken sent from hub is being regenerated and used with different signature
=> Fix login with token from hub

CHANGELOG.md, package.json, yarn.lock
dApps are not loading in Chrome on iOS mobile because webview provider because isMobileWebview helper wrongly detects RN iframe and tries to perform login, and no response is received
Fix in webview provider package and upgrade
=> Upgrade webview provider

CHANGELOG.md, package.json, src/managers/TransactionManager/TransactionManager.ts
- executing `computeTransactionHash` on every signedTx it will crash for no reason
- send transactions and sometimes it will crash
Issue exists on version `5.0.10` of sdk-dapp.
- computeTransactionHash usage
- remove `computeTransactionHash` and use hash from API response
=> Fix computeHash Transaction of undefined

CHANGELOG.md, package.json, src/managers/internal/ToastManager/ToastManager.ts, src/managers/internal/ToastManager/helpers/createToastsFromTransactions.ts, src/utils/transactions/getTransactionsHistory/helpers/mapServerTransactionsToListItems.ts
Too many calls are made to /transactions endpoint when tracking transactions
Go to https://devnet.template-dapp.multiversx.com/ and make a Swap & Lock action and look in the Network tab
Both [mapServerTransactionsToListItems](https://github.com/multiversx/mx-sdk-dapp/blob/e53269635eb28735fcb8b32f6fbedd49fbfe226c/src/utils/transactions/getTransactionsHistory/helpers/mapServerTransactionsToListItems.ts#L44) and [checkBatch](https://github.com/multiversx/mx-sdk-dapp/blob/e53269635eb28735fcb8b32f6fbedd49fbfe226c/src/methods/trackTransactions/helpers/checkTransactionStatus/checkBatch.ts#L130) were calling [getServerTransactionsByHashes](https://github.com/multiversx/mx-sdk-dapp/blob/e53269635eb28735fcb8b32f6fbedd49fbfe226c/src/apiCalls/transactions/getServerTransactionsByHashes.ts#L7C14-L7C43). …
=> Fix duplicate calls to getTransactionsByHashes

README.md, package.json, src/managers/TransactionManager/TransactionManager.ts, src/managers/TransactionManager/TransactionManager.types.ts, src/managers/TransactionManager/helpers/sessionCallbacks.ts, src/methods/initApp/initApp.ts, src/methods/trackTransactions/helpers/checkTransactionStatus/runSessionCallbacks.ts
Users cannot set callbacks for a specific transaction session
Registering callbacks after `initApp` using TransactionManager.registerCallbacks` is always overwriting the global callbacks function
Both `initApp` and `TransactionManager.registerCallbacks` use the same object for reference
Allow setting the callbacks by referencing the `sessionId`
=> Added session callbacks

CHANGELOG.md, src/providers/ProviderFactory.ts
Unable to create new custom providers that implement `CrossWindowStrategy`
Do a new provider like
```
import { CrossWindowProviderStrategy } from '@multiversx/sdk-dapp/out/providers/strategies/CrossWindowProviderStrategy/CrossWindowProviderStrategy';
export class CustomProvider extends CrossWindowProviderStrategy {
getType() {
return 'customProvider';
}
}
```
CrossWindowProvider gets reset and does not login
Detect constructor and if constructor is CrossWindow, skip clearing initiated login
=> Fix inherit cross window provider

CHANGELOG.md, package.json, src/hooks/login/useWalletConnectV2Login.ts
Unable to sign transactions on web wallet with walletconnect provider. Redirected to walletUrl sign hook
`initiateLogin` is required even when logged in
- Made a helper to check if logged in as wallet connect. This helper checks both `loginMethod` and `providerRef.current`. Previously, providerRef.current shown `wallet` when `loginMethod` showed `walletconnectv2`.
- Skip clearing address and account from store if logged in `initiateLogin`
=> Fixed unable to sign transactions on web wallet with walletconnect provider
