README.md, package-lock.json, package.json
Update: erdjs, dapp-utils, change license
=> Update erdjs and dapp-utils

src/components/TransactionSender/index.ts, src/components/TransactionsTracker/TransactionStatusTracker.tsx, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithLedger.tsx, src/redux/selectors/transactionsSelectors.ts, src/redux/slices/transactionsSlice.ts, src/services/transactions/sendTransactions.ts, src/services/transactions/signTransactions.tsx, src/types/transactions.ts, src/utils/smartContracts.ts
… completedThreshold customization
=> Allow customization of completed threshold for sc calls with multiple @ok

package.json, src/UI/TxDetails/index.tsx, src/UI/walletConnect/WalletConnectLoginButton/lightning.svg, src/UI/walletConnect/WalletConnectLoginContainer/index.tsx
Add `showIsLessThanDecimalsLabel` flag to denominate
=> Update denominate function

example/package-lock.json, package-lock.json, package.json, src/components/TransactionsTracker/TransactionStatusTracker.tsx, src/models/newTransaction.ts, src/redux/slices/transactionsSlice.ts, src/utils/account/addressIsValid.ts, src/utils/smartContracts.ts, src/utils/transactions/builtCallbackUrl.ts, src/utils/transactions/getTokenFromData.ts, src/utils/transactions/tests/getNftFromData.test.ts, src/utils/transactions/transactionStateByStatus.ts
=> Fix getting token from data

src/components/ProviderInitializer.tsx, src/utils/account/refreshAccount.tsx
Currently we do not set the username in the store. Can we add it?
=> feat: add username on account data

package.json, src/components/ProviderInitializer.tsx, yarn.lock
[+] updated erdjs-wallet-connect-provider to 2.1.0-alpha.3
[-] reverted tryAuthenticateWalletUser initalize on LoginMethodsEnum.none
=> fix wallet & walletconnect v2 login

package.json, src/UI/LoginButton/LoginButton.tsx, src/assets/sass/themes/theme.scss, yarn.lock
* fix login button custom class name
* 2.0.0-beta.10
* remove unnecessary code from theme
=> 2.0.0-beta.10

package.json, src/UI/SignTransactionsModals/SignWithWalletConnectModal/index.tsx, src/UI/walletConnect/WalletConnectLoginContainer/index.tsx, src/constants/index.ts, src/hooks/login/useWalletConnectLogin.ts, src/hooks/login/useWalletConnectV2Login.ts, src/hooks/transactions/useCancelWalletConnectAction.tsx, src/providers/utils.ts, src/types/dapp-provider.ts, src/types/enums.ts, yarn.lock
[+] updated @elrondnetwork/erdjs-wallet-connect-provider to 2.1.0-alpha.6
[+] prevent the login with WalletConnect ( v1 and v2 ) if the login modal was closed
[+] V1: send a erd_cancelAction custom message when the tx modal is closed
[+] V2: send a erd_cancelAction session_message when the tx modal is closed
=> WalletConnect cancelAction

package.json, src/hooks/login/useWalletConnectV2Login.ts, src/hooks/transactions/useCancelWalletConnectAction.tsx, src/providers/utils.ts, src/types/dapp-provider.ts, src/types/enums.ts, yarn.lock
[-] remove session_events flow since the dapp is not the controller,moved SIGN_LOGIN_TOKEN functionality to requests
[+] update @elrondnetwork/erdjs-wallet-connect-provider to 2.1.0-alpha.9
=> WalletConnect 2 Custom Requests

src/UI/walletConnect/WalletConnectLoginContainer/index.tsx
[+] show a message on the wc2 login card that can lead the user to the wc1 implementation/qr-code
=> show legacy switch on wc2 login

src/UI/TransactionsTable/TransactionsTable.tsx, src/UI/TransactionsToastList/components/TransactionToast/TransactionToastContent.tsx, src/UI/ledger/LedgerLoginContainer/ConfirmAddress.tsx, src/UI/ledger/LedgerLoginContainer/LedgerConnect.tsx, src/UI/pages/UnlockPage/index.tsx, src/UI/walletConnect/WalletConnectLoginContainer/index.tsx, src/assets/sass/themes/background.scss, src/assets/sass/themes/theme.scss, src/assets/sass/themes/type.scss
[-] remove global styles from scss, use globalStyles on affected elements
=> [-] remove global styles from scss

CHANGELOG.md, src/UI/DappModal/hooks/useDappModal.ts, src/hooks/index.ts, src/hooks/userInterface/index.ts, src/hooks/userInterface/useIsDappModalVisible.ts
Allow inspecting if dapp modal is visible
=> Add dapp modal visibility flag

CHANGELOG.md, src/apiCalls/accounts/getAccountFromApi.ts, src/apiCalls/endpoints.ts
- switch using getting account information from address endpoint to account endpoint, as some information was not available there, like `txCount` and `scrCount`
=> Fix account endpoint

CHANGELOG.md, package.json, yarn.lock
Update @elrondnetwork/erdjs-wallet-connect-provider to 2.1.0-beta.1 with @walletconnect 2.0.0-rc.3
=> Update @elrondnetwork/erdjs-wallet-connect-provider to 2.1.0-beta.1

CHANGELOG.md, src/components/TransactionSender/TransactionSender.ts, src/hooks/transactions/useSignTransactions.tsx, src/reduxStore/slices/transactionsSlice.ts, src/types/transactions.types.ts
- Safari cancels requestis on redirect, so transactions will not get sent unless redirecting is done after sending
=> Delegate redirecting after signing to TreansactionSender

CHANGELOG.md, src/UI/TimeAgo/TimeAgo.tsx
- allow TimeAgo to be used inside p tag
=> Fix TimeAgo HTML tag

CHANGELOG.md, package.json, src/hooks/login/useWalletConnectV2Login.ts, src/providers/accountProvider.ts, src/providers/utils.ts, yarn.lock
[+] Updated WalletConnect provider to 2.1.0-beta.3
[+] Renamed provider to WalletConnectV2Provider
=> Updated WalletConnect provider to 2.1.0-beta.3

CHANGELOG.md, package.json, src/UI/CopyButton/helpers/copyToClipboard.tsx, src/UI/DappModal/components/DappModal.tsx, src/UI/TransactionInfo/components/EventsList/EventsList.tsx, src/UI/TransactionInfo/components/ScResultsList/ScResultsList.tsx, src/UI/TransactionsToastList/index.tsx, src/UI/Trim/Trim.tsx, src/components/ProviderInitializer.tsx, src/components/TransactionSender/TransactionSender.ts, src/hooks/transactions/useParseSignedTransactions.tsx, src/utils/transactions/transactionInfoHelpers/useDataDecodeMethod.ts
* Add document and window guard for Next.js
=> Fix window and document undefined (#464)

CHANGELOG.md, src/hooks/transactions/helpers/index.ts, src/hooks/transactions/helpers/useSetTransactionNonces.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
- Make both `useSignTransactions` and `useSignTransactionsWithDevice` consume data from `useSignTransactionsCommonData` where incremental nonces are set for transactions in `transactionsToSign` store object
=> Extract useSetTransactionNonces

package.json
=> Allow compatible versions of peer deps - fixes #483

CHANGELOG.md, src/hooks/account/useGetIsLoggedIn.ts, src/hooks/account/useGetLoginInfo.ts, src/wrappers/AxiosInterceptorContext/components/AxiosInterceptor.tsx, src/wrappers/AxiosInterceptorContext/components/AxiosInterceptorContextProvider.tsx, src/wrappers/AxiosInterceptorContext/components/LoginInfoListener.tsx
* Refactor loginHooks to first provide infor from axiosContext and change interface containing isLoggedIn
=> Uniform isLoggen hook response (#511)

.github/workflows/npm-publish.yml, CHANGELOG.md, package.json
Update changelog, increment version, create PR
=> New version release

CHANGELOG.md, package.json, yarn.lock
This reverts commit 6f0efbe611d0929aab762fcb33b83947be1b9d7b.
=> Revert "increase hw-provider package version"

CHANGELOG.md, src/components/ProviderInitializer.tsx, src/hooks/account/useGetAccountProvider.ts, src/hooks/login/useWebViewLogin.ts, src/providers/webviewProvider/index.ts, src/providers/webviewProvider/requestMethods.ts, src/providers/webviewProvider/webviewProvider.ts, src/services/nativeAuth/helpers/loginWithNativeAuthToken.ts, src/services/transactions/utils.ts, src/types/enums.types.ts, src/utils/platform/detectCurrentPlatform.ts, src/wrappers/DappProvider/index.tsx
This PR adds the ability to support a webview provider, to allow dApp to add support for xPortal HUB integration
=> add webview provider to be able to integrate dapps into xPortal

src/utils/platform/detectCurrentPlatform.ts
Trying to get the latest version running with NextJs. Overall compatibility seems broken since ~v2.3.0
Potentially more is needed
=> Add further SSR support

CHANGELOG.md, package.json, src/providers/webviewProvider/webviewProvider.ts, src/utils/parseNavigationParams.ts
* Fix Next.js access to window
=> Next js fixes (#728)

CHANGELOG.md, src/UI/ExplorerLink/ExplorerLink.tsx, src/components/TransactionSender/TransactionSender.ts, src/hooks/transactions/useParseSignedTransactions.tsx, src/hooks/transactions/useSignTransactions.tsx, src/providers/webviewProvider/webviewProvider.ts, src/utils/index.ts, src/utils/isWindowAvailable.ts, src/utils/parseNavigationParams.ts, src/utils/transactions/builtCallbackUrl.ts, src/utils/transactions/index.ts, src/utils/transactions/removeTransactionParamsFromUrl.ts, src/utils/transactions/tests/removeTransactionParamsFromUrl.test.ts, yarn.lock
=> [FIX] Fixed transactions signing to prevent clearing of URL search params

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/SignWithDeviceModal.tsx, src/types/transactions.types.ts
- Guardian Screen needs access to address in order to build the guardian provider
=> Extend guardian screen definition

CHANGELOG.md, package.json, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, yarn.lock
* new extension provider version with guardian signing
* version bump, changelog
-
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Ag new extension provider (#758)

CHANGELOG.md, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsCommonData.tsx
- nonce management solution was causing issues on devnet-wallet
Issue exists on version `2.13.4` of sdk-dapp.
- needs investigating
- revert changes
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Tm revert nonce updates

CHANGELOG.md, src/hooks/transactions/useSignTransactionsCommonData.tsx, src/models/newTransaction.ts, src/services/transactions/sendTransactions.ts, src/types/transactions.types.ts
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] Added flag `preventNonceUpdate` to prevent nonce update

CHANGELOG.md, src/apiCalls/economics/getEconomicsInfo.ts, src/apiCalls/economics/index.ts, src/apiCalls/index.ts, src/hooks/economics/index.ts, src/hooks/economics/useGetEgldPrice.ts, src/hooks/index.ts, src/hooks/transactions/useGetTokenDetails.tsx
- Added `type` to token data on sign screen, `getEconomicsInfo`, and `useGetEgldPrice` hook
[x] No
[] Yes
[x] Yes
[] User testing
[] Unit tests
=> Egld price and economics

CHANGELOG.md, src/hooks/transactions/batch/useSendBatchTransactions.ts, src/utils/isWindowAvailable.ts
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix/window location for RN

CHANGELOG.md, src/hooks/transactions/useParseMultiEsdtTransferData.ts
ESDTNft transactions data parsing 
Issue exists on version `2.14.3` of sdk-dapp.
missing multiTxData on single ESDT transactions
[x] No
[] Yes
[x] Yes
[] Unit tests
=> fix esdt transactions parsing not returning multiTxData

CHANGELOG.md, src/UI/TransactionDetails/components/TransactionDetailsBody.tsx, src/UI/TransactionsToastList/components/TransactionToast/components/DefaultToastDeleteButton.tsx, src/UI/TransactionsToastList/components/TransactionToast/components/TransactionToastContent.tsx
Add datatestids to toast elements
Issue exists on version `2.14.3` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add toast datatestids

CHANGELOG.md, src/services/nativeAuth/methods/getNativeAuthConfig.ts, src/services/nativeAuth/nativeAuth.ts, src/types/login.types.ts
Added extraInfo param for generating nativeAuth token
[x] No
[] Yes
[x] Yes
[] Unit tests
=> added extraInfo param for generating nativeAuth token

CHANGELOG.md, src/UI/ledger/LedgerLoginButton/LedgerLoginButton.tsx, src/UI/walletConnect/WalletConnectLoginButton/WalletConnectLoginButton.tsx, src/UI/webWallet/WebWalletLoginButton/WebWalletLoginButton.tsx
- add datatestids to login buttons
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add datatestids to buttons

CHANGELOG.md, src/UI/ledger/LedgerLoginContainer/AddressTable.tsx, src/utils/account/tests/getSearchParamAddress.test.ts, yarn.lock
Added `data-testid` to `AddressTable` component
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] Added `data-testid` to `AddressTable` component

README.md
[x] No
[] Yes
[x] Yes
[] Unit tests
=> update live demo URL

CHANGELOG.md, src/hooks/login/useWalletConnectV2Login.ts
Log the uri on the debug environment for WalletConnect
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] also log the uri on the debug environment for WalletConnect

CHANGELOG.md, src/providers/webviewProvider/webviewProvider.ts
[x] No
[] Yes
[x] Yes
[] Unit tests
=> add ability to sign messages in webview provider

CHANGELOG.md, src/UI/TransactionData/TransactionData.tsx, src/constants/dataTestIds.enum.ts, src/constants/errorsMessages.ts, src/hooks/transactions/useSignMultipleTransactions.tsx, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
Prevent signing transactions with sender different from current account
Added dataTestIds from `DataTestIdsEnum` 
[x] No
[] Yes
[x] Yes
[x] Unit tests
=> [+] Prevent signing transactions with sender different from current account

CHANGELOG.md, package.json, yarn.lock
support usernames in `sdk-web-wallet-provider`
=> Update sdk web wallet provider

CHANGELOG.md, README.md, executeBuildCommand.js, src/constants/network.ts, src/types/enums.types.ts, src/wrappers/DappProvider/DappProvider.tsx
Add (temporary) support for devnet2 chain
=> Add (temporary) support for devnet2 chain

CHANGELOG.md, src/UI/CopyButton/CopyButton.tsx
Extend `UI/CopyButton` component icons, allow different icons to be provided
[x] No
[] Yes
[x] Yes
[] Unit tests
=> [+] Extend UI/CopyButton icons

CHANGELOG.md, src/UI/TransactionsToastList/TransactionsToastList.tsx, src/reduxStore/slices/toastsSlice.ts
Duplicate custom toasts with the same ID
Issue exists on version `2.20.6` of sdk-dapp.
addCustomToast function from the toastsSslice
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent duplicate custom toasts with the same ID

CHANGELOG.md, src/hooks/login/useLoginService.ts
###Feature
-
-
-
Return the native auth token when refreshing the token
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Ag refresh native auth token

src/UI/ledger/LedgerLoginContainer/AddressTable/AddressTable.tsx
[x] No
[] Yes
[x] Yes
[] Unit tests
=> disabled indexes optional

.github/workflows/run-template-dapps-integration.yml, CHANGELOG.md, scripts/template-dapps-integration.sh
Add integration tests for template dApps.
Verify the latest changes on the template dApps to prevent possible breakings on the production builds.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Integration tests

CHANGELOG.md, package.json, yarn.lock
Update the @multiversx/sdk-wallet-connect-provider provider to 4.0.4 (@walletconnect 2.10.2)
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Update the @multiversx/sdk-wallet-connect-provider provider to 4.0.4

CHANGELOG.md, executeBuildCommand.js, src/constants/index.ts, src/utils/transactions/builtCallbackUrl.ts, src/utils/transactions/removeTransactionParamsFromUrl.ts, src/utils/transactions/tests/builtCallbackUrl.test.ts
Allow inspection of sdk-dapp-version in walletUrl communication for debugging purposes
Issue exists on version `2.22.5` of sdk-dapp.
Unable to debug sdk-dapp issues in some interactions with wallet
Modify esbuild command and add version to callbackUrl
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Added sdk-dapp-version to walletUrl communication

CHANGELOG.md, src/models/newTransaction.ts, src/services/transactions/signTransactions.ts, src/utils/operations/calculateFeeLimit.ts, src/utils/transactions/index.ts, src/utils/transactions/isGuardianTx.tsx, src/utils/transactions/parseTransactionAfterSigning.ts, src/utils/transactions/tests/isGuardianTx.test.ts, yarn.lock
Removed `senderUsername` and `receiverUsername` for `SetGuardian` transactions 
[x] Yes
[x] Unit tests
=> Removed `senderUsername` and `receiverUsername` for `SetGuardian` tx

CHANGELOG.md, package.json, src/models/TransactionStatus.ts, src/services/transactions/getTransactionsDetails.ts, src/utils/operations/calculateFeeLimit.ts, yarn.lock
Remove `sdk-network-providers` from the dependencies
Issue exists on version `2.26` of sdk-dapp.
The package isn't used extensively and its existence is not necessary anymore
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Remove sdk-network-providers from the dependencies

CHANGELOG.md, src/providers/webviewProvider/requestMethods.ts, src/providers/webviewProvider/webviewProvider.ts, yarn.lock
Adds custom message request capability to webview provider
[x] No
[] Yes
[x] Yes
[] Unit tests
=> custom messages for webview provider

CHANGELOG.md, src/UI/walletConnect/WalletConnectLoginButton/WalletConnectLoginButton.tsx, src/UI/walletConnect/WalletConnectLoginButton/types.ts, src/UI/walletConnect/WalletConnectLoginContainer/WalletConnectLoginContainer.tsx, src/UI/walletConnect/WalletConnectLoginContainer/WalletConnectLoginContent/WalletConnectLoginContent.tsx, src/UI/walletConnect/WalletConnectLoginContainer/types.ts, src/hooks/login/useWalletConnectV2Login.ts
###Feature
Added the option for custom reuquests registration for wallet connect 
[x] No
[] Yes
[x] Yes
[] Unit tests
=> add custom request option for WC button/hook

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, src/components/ProviderInitializer/helpers/getMultiSigLoginToken.ts, src/components/ProviderInitializer/helpers/index.ts, src/components/ProviderInitializer/helpers/tests/getMultiSigLoginToken.test.ts
Web Wallet login needs to be able to transmit a multisig contract address to sdk-dapp
Issue exists on version `2.28.0` of sdk-dapp.
Extract from new URL search params address + signature + **multisig** and add that information to the nativeAuth saved loginToken
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Support multisig token login

CHANGELOG.md, src/UI/TransactionsToastList/components/TransactionToast/TransactionToast.tsx
Added toast wrapper id in order to target individual toast
2.28.2
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Added transaction toast wrapper id

package.json, src/components/ProviderInitializer/ProviderInitializer.tsx, src/hooks/login/useWalletConnectV2Login.ts, src/reduxStore/slices/loginInfoSlice.ts, yarn.lock
Issue exists on version `2.28.7-alpha.7` of sdk-dapp.
Provider initialization is being done before the `chainID` which triggers the following error: `Missing or invalid. request() chainId: mvx:-1`
Wait until chainID is available before intializing the providers.
Cleanup unnecessary conditions in walletConnect initialization
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Update walletConnect initialization

package.json, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmReceiver/ConfirmReceiver.tsx, yarn.lock
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed receiver data test identifier.

package.json, src/UI/Balance/Balance.tsx
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Mm fix receiver data testid

CHANGELOG.md, package.json, src/UI/Balance/Balance.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/SignStepBody.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmAmount/components/ConfirmAmountData/ConfirmAmountData.tsx, src/UI/SignTransactionsModals/SignWithDeviceModal/components/components/ConfirmReceiver/ConfirmReceiver.tsx, src/hooks/transactions/useSignMultipleTransactions.tsx, yarn.lock
Sign step not working
Issue exists on version `2.28.7-alpha.23` of sdk-dapp.
False positive for all signed by guardian
Check for guardian
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix Sign step progress

package.json, src/UI/Balance/Balance.tsx
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fixed code.

CHANGELOG.md, src/utils/logout.ts
Wallet logout not working
Issue exists on version `2.29.0-beta.2` of sdk-dapp.
Early redirect
Stop logout redirect for wallet provider
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix wallet logout

CHANGELOG.md, package.json, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, yarn.lock
Cross window 2FA signing
Ledger guardian signing happening with page reload
Use cross-window provider
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Cross window 2FA signing

CHANGELOG.md, package.json, src/wrappers/AxiosInterceptorContext/components/LoginInfoListener.tsx
Ledger login cross-window not reporting signature
Issue exists on version `2.29.0-beta.14` of sdk-dapp.
useGetLoginInfo returning incomplete information
LoginInfoListener useEffect parameter change to listen to whole `loginInfo` object
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix ledger login

package.json, src/utils/logout.ts
Allow preventing logout from other tabs
Issue exists on version `2.29.0-beta.16` of sdk-dapp.
extend `logout` function
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Extend logout with options

CHANGELOG.md, package.json, src/UI/webWallet/CrossWindowLoginButton/CrossWindowLoginButton.tsx, src/hooks/login/useCrossWindowLogin.ts, src/hooks/signMessage/useSignMessage.ts, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, src/hooks/transactions/useSignTransactions.tsx, src/services/transactions/sendBatchTransactions.ts, src/services/transactions/sendTransactions.ts, src/types/transactions.types.ts, src/utils/account/signMessage.ts, src/utils/logout.ts, yarn.lock
---------
Fix Safari Cross Window Signing
Issue exists on version `2.29.0-beta.19` of sdk-dapp.
Async calls before opening the wallet tab blocks opening
Add a confirmation modal in cross window provider before opening the wallet window
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Upgrade cross window provider (#1106)

CHANGELOG.md, package.json
=> 2.29.0 (#1121)

CHANGELOG.md, package.json, yarn.lock
Updated sdk-core version to 13.0.0
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Updated sdk-core version to 13.0.0

CHANGELOG.md, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx
Capturing ledger 2FA code not working on cross window
Issue exists on version `2.29.0` of sdk-dapp.
Browser async action blocks popup window
Revert to URL communication
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Revert capturing ledger 2FA on URL

CHANGELOG.md, src/providers/experimentalWebViewProvider/ExperimentalWebviewProvider.ts, src/providers/experimentalWebViewProvider/helpers/webviewProviderEventHandler.ts
Origin mismatch
Issue exists on version `2.30.1` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: fix mobile webview communication

CHANGELOG.md, package.json, src/apiCalls/transactions/getTransactions.ts, src/apiCalls/transactions/getTransactionsByHashes.ts, src/utils/account/getAccountShard.tsx
=> Added axios types

CHANGELOG.md, package.json, yarn.lock
- Updated @multiversx/sdk-wallet-connect-provider to 4.1.2 ( @WalletConnect 2.12.2 )
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Update WalletConnect 4.1.2

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, yarn.lock
Account information isn't refreshed upon network change due to an additional address check.
Issue exists on version `2.31.3` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] No
[] Unit tests
=> Removed unnecessary address check.

CHANGELOG.md, package.json, yarn.lock
Issue exists on version `2.31.6` of sdk-dapp.
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: fix android communication

CHANGELOG.md, src/constants/browser.ts, src/constants/index.ts, src/hooks/login/useCrossWindowLogin.ts
Firefox not opening cross window wallet tab
Firefox update
Added FF Windows to browser constants
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Add firefox cross window popover

CHANGELOG.md, package.json, yarn.lock
No messages are received from Android Webview
Issue exists on version `2.32.0` of sdk-dapp.
webview-provider message handler
[x] No
[] Yes
[x] Yes
[] Unit tests
=> ExperimentalWebviewProvider: Fix incoming messages from android webview

CHANGELOG.md, src/UI/FormatAmount/FormatAmount.tsx, yarn.lock
Format amount component falls back to hardcoded egld label
Issue exists on version `2.32.6` of sdk-dapp.
Hardcoded egld label in format amount component
Use the egld label from active network state
[x] No
[] Yes
[x] Yes
[] Unit tests
=> fix hardcoded egld label in format ammount component

CHANGELOG.md, package.json, src/UI/index.ts, src/UI/webWallet/XaliasCrossWindowLoginButton/XaliasCrossWindowLoginButton.tsx, src/UI/webWallet/XaliasCrossWindowLoginButton/index.tsx, src/hooks/login/useCrossWindowLogin.ts
Added `XaliasCrossWindowLoginButton`
Issue exists on version `2.32.10` of sdk-dapp.
x-Alias login working only on URL
Add`XaliasCrossWindowLoginButton`
[x] No
[] Yes
[x] Yes
[] Unit tests
=> X-alias-cross-window-login

CHANGELOG.md, package.json, yarn.lock
Related to: https://github.com/multiversx/mx-sdk-js-webview-provider/pull/6
=> ExperimentalWebviewProvider: full webkit support

CHANGELOG.md, src/apiCalls/accounts/getAccountFromApi.ts, src/wrappers/AuthenticatedRoutesWrapper/helpers/tests/matchPath.test.ts
=> Add match path tests

CHANGELOG.md, src/components/ProviderInitializer/ProviderInitializer.tsx, src/utils/account/refreshAccount.tsx
Network config is updated in store regardless
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Prevent network update if there are no changes

CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx, src/hooks/login/useMetamaskProxyLogin.ts, src/types/network.types.ts, yarn.lock
Issue exists on version `2.38.0` of sdk-dapp.
Missing handles in provider
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Fix metamask-proxy-provider: logout and cancel handles

CHANGELOG.md, package.json, src/lib/sdkDappUtils.ts, src/types/enums.types.ts, yarn.lock
Revert changes for sdk-dapp-utils version change
[x] No
[] Yes
[x] Yes
[] Unit tests
=> revert changes

CHANGELOG.md, package.json, src/hooks/login/usePasskeyLogin.ts, yarn.lock
###Feature
Add create account functionality for passkey wallets
[x] No
[] Yes
[x] Yes
[] Unit tests
=> add create account for passkey wallets

CHANGELOG.md, package.json, yarn.lock
Passkey login fails
Issue exists on version `2.40.5` of sdk-dapp.
Public address creation fails in passkey provider package
Derive public address from private key
Incremented passkey provider version
[x] No
[] Yes
[x] Yes
[] Unit tests
=> bump passkey provider version

src/utils/account/addressIsValid.ts
[x] No
[] Yes
[x] Yes
[] Unit tests
=> fix addressValid check

CHANGELOG.md, src/UI/SignTransactionsModals/SignWithDeviceModal/signWithDeviceModal.types.ts, src/UI/types/withClassname.types.ts, src/hooks/transactions/helpers/checkNeedsGuardianSigning.ts, src/hooks/transactions/useGetSignedTransactions.ts, src/hooks/transactions/useSignTransactions.tsx, src/hooks/transactions/useSignTransactionsWithDevice.tsx, src/reduxStore/selectors/transactionsSelectors.ts, src/types/transactions.types.ts
Unable to sign multiple guarded transactions on URL
URL length limitation
Moved 2FA signing from URL to Cross-window wallet
Fix signedTransactions type
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Cross-window-2fa

.github/pull_request_template.md, CHANGELOG.md, package.json, yarn.lock
- Updated `@multiversx/sdk-wallet-connect-provider` to 4.1.4
- Updated markdown on pull_request_template
[x] No
[] Yes
[x] Yes
[] Unit tests
=> Update WalletConnect Provider

CHANGELOG.md, package.json, src/hooks/login/useLoginService.ts, src/hooks/signMessage/getVerifier.ts, yarn.lock
=> 3.0.1 Update sdk-core (#1283)

CHANGELOG.md, src/UI/pages/UnlockPage/index.tsx, src/utils/redirect.ts, src/utils/window/index.ts, src/utils/window/redirect.ts
sdk-dapp used in extension environment redirects to the origin
If URL does not start with HTTP do a browser reload
=> Wrap `location.assign` in redirect function

CHANGELOG.md, package.json, src/components/ProviderInitializer/ProviderInitializer.tsx, src/components/ProviderInitializer/helpers/getIframeProvider.ts, src/hooks/login/useIframeLogin.ts, src/reduxStore/commonActions.ts, src/reduxStore/slices/loginInfoSlice.ts
Fixed passkey-provider loading issues
Issue exist when reloading on application that was connected through iframe to passkey-provider
Only iframe login was saved
Added an option for iframe login type
=> Fix passkey provider

src/UI/TransactionsTable/TransactionsTable.tsx
=> Fix React Error: Conditional rendering of hook

src/UI/TransactionsTable/TransactionsTable.tsx
https://react.dev/errors/310
Issue exists on version `3.0.21` of sdk-dapp.
=> Fix: Minified React error #310

src/UI/TransactionsTable/TransactionsTable.tsx
Minification errors. Ref: https://react.dev/errors/310
Issue exists on version `3.0.22` of sdk-dapp.
=> Fix deps array which can cause minification errors

CHANGELOG.md, package.json, src/UI/walletConnect/WalletConnectLoginContainer/WalletConnectLoginContent/WalletConnectLoginContent.tsx, yarn.lock
- Show the loading state on all functional components until ready
- Updated @multiversx/sdk-wallet-connect-provider to 5.0.2
=> WalletConnect: Show deeplink only if ready

CHANGELOG.md, src/UI/LoadingDots/LoadingDots.tsx, src/UI/Pagination/Pagination.tsx, src/UI/Pagination/components/PaginationEllipsisForm/PaginationEllipsisForm.tsx, src/UI/Pagination/components/PaginationEllipsisForm/index.ts, src/UI/Pagination/components/PaginationEllipsisForm/paginationEllipsisFormStyles.scss, src/UI/Pagination/paginationStyles.scss, yarn.lock
Add search tooltip to the Ledger address table pagination for easy navigation between pages.
Feature doesn't exist on `v3.1.7` of `sdk-dapp`.
=> Ledger Address Table Pagination Search Tooltip

CHANGELOG.md, package.json, src/utils/platform/getIsExtensionAvailable.ts, yarn.lock
`elrondWallet` will be replaced by `multiversxWallet`
Branding name
Add  `multiversxWallet`.
=> Add multiversxWallet

CHANGELOG.md, src/hooks/transactions/index.ts
Wrong export of `useTransactionsTracker`
=> Fix tracker export

CHANGELOG.md, package.json, src/models/newTransaction.ts, yarn.lock
Add support for relayed transactions
- update `newTransaction`
- upgrade sdk-core
- upgrade sdk-web-wallet-provider
=> Relayed transactions

CHANGELOG.md, src/hooks/login/helpers/clearInitiatedLogins.ts
Account remains in store in some cases after logour / partial logout
Clear account from store on login
=> Added account cleanup on login

CHANGELOG.md, src/apiCalls/accounts/getAccountFromApi.ts, src/utils/account/getAccount.tsx
Allow setting apiAddress options when getting the account
=> Get account options

CHANGELOG.md, package.json, src/methods/account/getLatestNonce.ts, src/react/account/useGetAccount.ts, src/react/account/useGetAccountInfo.ts, src/react/account/useGetIsLoggedIn.ts, src/react/account/useGetLatestNonce.ts, src/react/loginInfo/useGetLoginInfo.ts, src/react/network/useGetNetworkConfig.ts, src/react/store/getReactStore.ts, src/react/store/useSelector.ts, src/react/transactions/useGetPendingTransactions.ts, src/react/transactions/useGetPendingTransactionsSessions.ts, src/react/transactions/useGetTransactionSessions.ts
React store unresponsive
Make imports relative
=> Fix react store imports

CHANGELOG.md, README.md, src/managers/NotificationsFeedManager/NotificationsFeedManager.ts, src/methods/initApp/initApp.types.ts, src/providers/DappProvider/DappProvider.ts, src/providers/DappProvider/helpers/login/login.ts, src/providers/DappProvider/helpers/logout/logout.ts, src/providers/DappProvider/helpers/signMessage/signMessageWithProvider.ts, src/providers/DappProvider/helpers/signMessage/verifyMessage.ts, src/store/storage/storageCallback.ts, src/types/index.ts, src/types/misc.types.ts
Improve documentation
Added return types
=> Update readme and methods

CHANGELOG.md, src/providers/strategies/helpers/signTransactions/helpers/getCommonData/getCommonData.ts, src/providers/strategies/helpers/signTransactions/signTransactions.ts, src/utils/formats/formatWithDot.ts
Added formatted gasPrice and gasLimit.
=> Add format gasLimit and gasPrice

CHANGELOG.md, src/providers/DappProvider/DappProvider.ts, src/providers/DappProvider/helpers/login/login.ts
Add support for custom login token
=> Add custom login token support

CHANGELOG.md, src/managers/internal/ToastManager/ToastManager.ts
Disable toast exclusion mechanism based o transaction timestamp
=> Allow toasts

CHANGELOG.md, package.json, src/providers/DappProvider/DappProvider.ts, src/providers/DappProvider/helpers/logout/logout.ts, src/providers/types/providerFactory.types.ts
- added safeguard for multiple logout actions
Issue exists on version `5.0.0-alpha.19` of sdk-dapp.
=> Add logout safeguard for multiple requests

CHANGELOG.md, src/managers/TransactionManager/TransactionManager.ts
Gas price, gas limit and data fields were not included in the transaction object.
=> Added plain transaction fields to transaction object.

CHANGELOG.md, src/managers/UnlockPanelManager/UnlockPanelManager.ts
=> Temp disable passkeys

CHANGELOG.md, package.json, src/utils/visual/switchTheme.ts
Changed `data-theme` in `data-mvx-theme`
=> Updated data-theme

CHANGELOG.md, src/methods/trackTransactions/helpers/checkTransactionStatus/checkBatch.ts, src/utils/account/refreshAccount.ts
The account balance did not update automatically after a transaction was completed.
=> Added refresh account after completed transactions

CHANGELOG.md, README.md
- add docs for clearing a custom toast using ToastManager
=> Add docs for closeToast

CHANGELOG.md, README.md
=> Added RN template to README

CHANGELOG.md, package.json, pnpm-lock.yaml, src/constants/providerFactory.constants.ts, src/providers/ProviderFactory.ts, src/providers/strategies/IframeProviderStrategy/IframeProviderStrategy.ts, src/providers/strategies/IframeProviderStrategy/types/iframe.types.ts, src/providers/types/providerFactory.types.ts
- temporary removed passkey until audit
Issue exists on version `5.2.1` of sdk-dapp.
=> Removed passkey and update metamask snap

CHANGELOG.md, package.json, pnpm-lock.yaml, src/store/actions/transactions/transactionsActions.ts
Custom error messages not showing
Use `updateSessionStatus` to update an error message
Error message was overwritten by `checkBatch`
Keep existing error message if set
=> Fix custom error message

CHANGELOG.md, src/store/actions/transactions/transactionsActions.ts
Error messages are getting overwritten by undefined
Create transactions with display for error message
Why not reading from immer objects are a proxy
Use current function
=> Fix state proxy
